version: "3"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "TODOAPP"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo_data
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopassword